from . import patient
from . import doctor
from . import appointment
from . import description
from . import wards
from . import pharmacy
from . import labraries
from . import billing_invoice
from . import department
